/*******************************************************************
 * Autogenerated by cudimot_gui
 *
 * Any changes made to this file will be overwritten if it is opened
 * in cudimot_gui!
 *******************************************************************/
#ifndef MODEL_H_INCLUDED
#define MODEL_H_INCLUDED

// Use double precision
typedef double MyType;

// Define numbers of parameters

// Variable parameters
#define NPARAMS 7 // fiso,fintra,kappa,beta,th,ph,psi

// Common fixed parameters
#define NCFP 2 // bvecs,bvals

// Voxelwise fixed parameters
#define NFIXP 1 // S0

// Model data structure
struct MODEL
{
  static int CFP_size[NCFP];
  static int FixP_size[NFIXP];
};
#endif
