"""
CUDIMOT GUI - Templates for autogenerated code
"""

HEADER = """\
/*******************************************************************
 * Autogenerated by cudimot_gui
 *
 * Any changes made to this file will be overwritten if it is opened
 * in cudimot_gui!
 *******************************************************************/
"""

MODELPARAMETERS_H = """\
#ifndef MODEL_H_INCLUDED
#define MODEL_H_INCLUDED

// Use {precision} precision
typedef {dtype} MyType;

// Define numbers of parameters

// Variable parameters
#define NPARAMS {n_param} // {param_names}

// Common fixed parameters
#define NCFP {n_cfp} // {cfp_names}

// Voxelwise fixed parameters
#define NFIXP {n_vfp} // {vfp_names}

// Model data structure
struct MODEL
{{
  static int CFP_size[NCFP];
  static int FixP_size[NFIXP];
}};
#endif
"""

MODELPARAMETERS_CC = """\
#include "modelparameters.h"

int MODEL::CFP_size[] = {{{cfp_sizes}}};
int MODEL::FixP_size[] = {{{vfp_sizes}}};
"""

MODELFUNCTIONS_H = """\
// Parameters in {name}
// P[0]: fiso
// P[1]: fintra
// P[2]: kappa
// P[3]: beta
// P[4]: th
// P[5]: ph
// P[6]: psi

// CFP[0:2] are bvecs 
// CFP[3] are bvals

// FixP[0] is S0

{code_support}

{code_fwdmodel}

{code_constraints_mcmc}

{code_derivatives_lm}

{code_constraints_lm}

{code_custom_priors}
"""

MODELPRIORS = """\
// For initialization
// fiso, fintra, kappa, th, ph
P_init[{param_inits}]

// Priors:
{bounds_spec}

{priors_spec}
"""

MAKEFILE = """\
# This is the Makefile for the CUDIMOT project
#
# The CUDIMOT project provides ...
#
# A CUDA compiler and toolkit must be installed

include $(FSLCONFDIR)/default.mk

PROJNAME = cudimot
MODELNAME = {name}
MODELDIR = {projdir}
CUDIMOT_SRCDIR = $(MODELDIR)/../..

LIBS     = -lfsl-warpfns -lfsl-basisfield -lfsl-meshclass  \\
           -lfsl-newimage -lfsl-miscmaths -lfsl-NewNifti   \\
           -lfsl-utils -lfsl-newran -lfsl-znz -lfsl-cprob

USRINCFLAGS = -I$(MODELDIR) -I$(FSLDIR)/include/armawrap

CUDIMOT_CUDA_OBJS = \\
    $(MODELDIR)/modelparameters.o \\
    init_gpu.o \\
    dMRI_Data.o \\
    Model.o \\
    Parameters.o \\
    GridSearch.o \\
    Levenberg_Marquardt.o \\
    MCMC.o \\
    BIC_AIC.o \\
    getPredictedSignal.o

CUDIMOT_OBJS = \\
    cudimot.o \\
    cudimotoptions.o

SCRIPTS  = \\
    $(CUDIMOT_SRCDIR)/utils/Run_dtifit.sh \\
    $(CUDIMOT_SRCDIR)/utils/jobs_wrapper.sh \\
    $(CUDIMOT_SRCDIR)/utils/initialise_Bingham.sh \\
    $(MODELDIR)/$(MODELNAME)_finish.sh \\
    $(MODELDIR)/Pipeline_$(MODELNAME).sh

XFILES   = \\
    cart2spherical \\
    getFanningOrientation \\
    initialise_Psi \\
    $(MODELNAME) \\
    cudimot_$(MODELNAME).sh \\
    merge_parts_$(MODELNAME) \\
    split_parts_$(MODELNAME) \\
    testFunctions_$(MODELNAME)

DATAFILES = \\
    $(MODELNAME)_priors \\
    $(MODELNAME).info

all: $(XFILES) $(DATAFILES)
clean: cleandata

cleandata:
	rm -rf $(DATAFILES)

%.o: $(CUDIMOT_SRCDIR)/%.cu
	$(NVCC) -c $(NVCCFLAGS) $^

%.o: $(CUDIMOT_SRCDIR)/%.cc
	$(CXX) -c $(CXXFLAGS) $^

cart2spherical: $(CUDIMOT_SRCDIR)/utils/cart2spherical.o
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS)

getFanningOrientation: $(CUDIMOT_SRCDIR)/utils/getFanningOrientation.o
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS)

initialise_Psi: $(CUDIMOT_SRCDIR)/utils/initialise_Psi.o
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS)

$(MODELNAME): $(CUDIMOT_SRCDIR)/cudimot.cc cudimotoptions.o $(CUDIMOT_CUDA_OBJS)
	$(NVCC) $(NVCCFLAGS) $(NVCCLDFLAGS) -o $@ $^

merge_parts_$(MODELNAME): $(CUDIMOT_SRCDIR)/merge_parts.cc cudimotoptions.o $(CUDIMOT_CUDA_OBJS)
	$(NVCC) $(NVCCFLAGS) $(NVCCLDFLAGS) -o $@ $^ -lboost_filesystem -lboost_system

split_parts_$(MODELNAME): $(CUDIMOT_SRCDIR)/split_parts.cc cudimotoptions.o $(CUDIMOT_CUDA_OBJS)
	$(NVCC) $(NVCCFLAGS) $(NVCCLDFLAGS) -o $@ $^ -lboost_filesystem -lboost_system

testFunctions_$(MODELNAME): $(CUDIMOT_SRCDIR)/testFunctions.cu $(MODELDIR)/modelparameters.o
	$(NVCC) $(NVCCFLAGS) $(NVCCLDFLAGS) -o $@ $^

cudimot_$(MODELNAME).sh : $(MODELNAME)
	$(CUDIMOT_SRCDIR)/generate_wrapper.sh $(MODELNAME)

$(MODELNAME).info : cudimot_$(MODELNAME).sh
	$(CUDIMOT_SRCDIR)/generate_info.sh $(MODELNAME)

$(MODELNAME)_priors:
	cp $(MODELDIR)/modelpriors $@
"""
