/*******************************************************************
 * Autogenerated by cudimot_gui
 *
 * Any changes made to this file will be overwritten if it is opened
 * in cudimot_gui!
 *******************************************************************/
#include "modelparameters.h"

int MODEL::CFP_size[] = {1};
int MODEL::FixP_size[] = {1};
